"""
Django settings for Almuerzos project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*e(gotyew#ib&1zz9(phwr0*1n8h_o$)u3o%(2)+jd(46a6fyn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','nora.cornershop.io','localhost','f18fd7c5.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestionAlmuerzos',
    'rest_framework',
    'django_celery_beat',
    'django_celery_results',
    'django_nose',
]

# Django-nose Measuring coverage
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

NOSE_ARGS = [
    '--with-coverage',
    '--cover-html',
    '--cover-html-dir=htmlcov',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Almuerzos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Almuerzos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'noraalmuerzos',
        'TEST': {
            'NAME': 'coverage_test_nora',
        },
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'DATABASE': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

############################## Variables de Slack ######################################
SLACK_CLIENT_ID='1135404625217.1148156261488' # Token del usuario Slack
SLACK_CLIENT_SECRET='0ff7afd872440d5e5f2f93435bc14713' # Id secreto del usuario
SLACK_VERIFICATION_TOKEN = '8qaDfPeXTRFrPnSqfBRxM3O3' # Token para verificar identidad Slack
SLACK_BOT_USER_TOKEN = 'xoxb-1135404625217-1137028203233-HWDUkAlskDF12WvXqIwF7zPo' # Token de un bot de Slack 
SLACK_USER_TOKEN='xoxp-1135404625217-1146618983024-1134690469476-fee830b1f5966e2c73cd411406abbae3'
ID_CHANNEL = 'C0136160H0X' # Este valor debe cambiarse al Id del canal del usuario que gestione, no importa como se llame el canal
##########################################################################################



############################## URL del programa  ######################################
#MENU_URL = 'https://nora.cornershop.io/menu/{}' # Descomentar esta variable para usar el programa
MENU_URL = 'https://f18fd7c5.ngrok.io/menu/{}' # Esta variable se debe comentar para usar el programa
##########################################################################################



############################## Autentificacion de Programa ######################################
LOGIN_REDIRECT_URL = reverse_lazy('gestion_nora')
LOGOUT_REDIRECT_URL = reverse_lazy('login')
##########################################################################################


 
############################## Configuracion Celery ######################################
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_BROKER_URL='redis://localhost:6379/0'
##########################################################################################







