# Generated by Django 3.0.6 on 2020-05-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_fuerte', models.CharField(max_length=30)),
                ('ensalada', models.CharField(blank=True, max_length=30)),
                ('postre', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionAlmuerzos.Empleado')),
                ('fechaHora', models.DateTimeField()),
                ('customizacion', models.CharField(blank=True, max_length=20)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAlmuerzos.Calendario')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAlmuerzos.Menu')),
            ],
            options={
                'unique_together': {('empleado', 'calendario')},
            },
        ),
    ]
