# Generated by Django 3.0.6 on 2020-05-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('fecha_id', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_fuerte', models.CharField(max_length=20)),
                ('ensalada', models.CharField(blank=True, max_length=20)),
                ('postre', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizacion', models.CharField(blank=True, max_length=20)),
                ('calendario_fecha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAlmuerzos.Calendario')),
                ('empleado_empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAlmuerzos.Empleado')),
                ('menu_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAlmuerzos.Menu')),
            ],
            options={
                'unique_together': {('empleado_empleado_id', 'calendario_fecha_id')},
            },
        ),
    ]
